### ISSUE TITLE
pytype re-add

### ISSUE THREAD

**Issue by Gorkowski** [uncscode/datacula#10]
Pytype was removed from the GitHub workflow, add this back when things are more functional.

**Comment by ngam** [comment]
😄 

Do you want to get this up on pypi too btw?

**Comment by Gorkowski** [comment]
YES YES.

It wasn't clear to me how you set that up in particular...but I also didn't look too deeply into it.

**Comment by ngam** [comment]
We need something like this `pypi.yml` file here: https://github.com/uncscode/particula/blob/main/.github/workflows/pypi.yml

Alternatively, we can squeeze datacula into particula, so that way we don't have to publish separate packages. 

Either way, I can deal with it and skim your edits early next week

**Comment by ngam** [comment]
Should we:
- [ ] move the content under particula and tag a new release

or

- [ ] make a new release here under a totally new package

?

**Comment by Gorkowski** [comment]
My initial inclination is: 
* [ ]  make a new release here under a totally new package

but I'm thinking there could be benefits to function recycling, moving under particula. 
would the imports be like
from particula.datacula import datastream

**Comment by Gorkowski** [comment]
After some more thinking, there are probably a lot of basic functions that both packages will use. We should move it under particula....even though I'll miss the datacula readme :)

**Comment by ngam** [comment]
We can do either
```
from particula.datacula import datastream
```
or 
```
from datacula import datastream
```
or both, but we should likely do the former (first one). 

The only pro (from packaging perspective) is that having it under particula is easier for now. There are easy workarounds for everything else. I will release 0.0.0 or 0.0.1 on pypi for now anyway, so that we can save that name (and readme). If both packages grow much bigger, we should definitely separate them

**Comment by ngam** [comment]
@Gorkowski https://pypi.org/project/datacula/

**Comment by ngam** [comment]
Once we have enough stuff in here, I can add datacula to conda as well

**Comment by ngam** [comment]
Also, it should work automatically now whenever you push a release, see: https://github.com/uncscode/datacula/actions/runs/4695701087/jobs/8325106748
